from ubuntu:latest
env DEBIAN_FRONTEND=noninteractive

run apt-get update
run apt-get install -y wget gnupg curl tmux ca-certificates

run curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | gpg --dearmor | tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null
run curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null
run curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key | gpg --dearmor | tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null

run echo 'deb [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main' > /etc/apt/sources.list.d/rabbitmq.list
run echo 'deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main' >> /etc/apt/sources.list.d/rabbitmq.list
run echo 'deb [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main' >> /etc/apt/sources.list.d/rabbitmq.list
run echo 'deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy main' >> /etc/apt/sources.list.d/rabbitmq.list

run apt-get update
run apt-get install -y rabbitmq-server --fix-missing

env RABBITMQ_USER=sa
env RABBITMQ_PASSWORD=12345678

copy ./configure.sh .
run chmod +x ./configure.sh

copy ./entrypoint.sh .
run chmod +x ./entrypoint.sh
cmd ./entrypoint.sh