name: Build and publish rabbit container

on:
  push:
    branches: [ "rabbit" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd dockerfile-rabbit
          docker login -u coderookieerick -p ${{ secrets.COMMON_DOCKER_IMAGES_TOKEN }}
          docker build -t common-rabbit .
          docker tag common-rabbit coderookieerick/common-rabbit
          docker push coderookieerick/common-rabbit:latest