name: Build and publish php container

on:
  push:
    branches: [ "php" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd dockerfile-php
          docker login -u coderookieerick -p ${{ secrets.COMMON_DOCKER_IMAGES_TOKEN }}
          docker build -t common-php .
          docker tag common-php coderookieerick/common-php
          docker push coderookieerick/common-php:latest