name: Node 9am build


on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
        with:
          ref: node
      - run: |
          cd dockerfile-node
          docker login -u coderookieerick -p ${{ secrets.COMMON_DOCKER_IMAGES_TOKEN }}
          docker build -t common-node .
          docker tag common-node coderookieerick/common-node
          docker push coderookieerick/common-node:latest