name: Scheduled build and publish rabbit container


on:
  schedule:
    - cron: "50 0 * * *"

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
        with:
          ref: rabbit
      - run: |
          cd dockerfile-rabbit
          docker login -u coderookieerick -p ${{ secrets.COMMON_DOCKER_IMAGES_TOKEN }}
          docker build -t common-rabbit .
          docker tag common-rabbit coderookieerick/common-rabbit
          docker push coderookieerick/common-rabbit:latest