name: Azurite 9pm build


on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
        with:
          ref: azurite
      - run: |
          cd dockerfile-azurite
          docker login -u coderookieerick -p ${{ secrets.COMMON_DOCKER_IMAGES_TOKEN }}
          docker build -t common-azurite .
          docker tag common-azurite coderookieerick/common-azurite
          docker push coderookieerick/common-azurite:latest